name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  tf-deploy:
    runs-on: ubuntu-latest
    container: { image: alpine }
    steps:
    - run: uname -a
    - run: cat /etc/alpine-release
    - run: touch /hello
    - run: ls /
