name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  tf-deploy:
    runs-on: ubuntu-latest
    container: docker://niceandgoodonline/tf-awscli:latest
    steps:
    - uses: actions/checkout@v3
    - name: testing
      run: |
        ls
        pwd
