name: Terraform Backend Deploy

on:
  workflow_dispatch:

jobs:
  tf-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SEC: ${{ secrets.AWS_SEC }}
      TF_EXT: ${{ secrets.TF_EXT }}
    container: docker://niceandgoodonline/tf-awscli:latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy soc-iac-k8s Backend Bucket
      run: |
        source .github/sh/aws_auth.sh
        source .github/sh/assume_tf_iamrole.sh
        source .github/sh/vars.sh
        cd terraform/backend/soc-iac-k8s-demo
        terraform init
        terraform apply -auto-approve
