name: Terraform Backend Deploy

on:
  workflow_dispatch:

jobs:
  tf-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_KEY: ${{ secrets.AWS_KEY }}
      AWS_SEC: ${{ secrets.AWS_SEC }}
      TF_EXT: ${{ secrets.TF_EXT }}
    container: docker://niceandgoodonline/tf-awscli:latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy Terramera Backend Bucket
      run: |
        echo $AWS_KEY || true
        source .github/sh/aws_auth.sh
        source .github/sh/assume_tf_iamrole.sh
        cd terraform/backend/terramera-demo
        source ./vars.sh
        terraform init
        terraform apply -auto-approve
